name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: 'Testing'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - run: npm install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      # Run the build command if it exists.
      - run: npm run build --if-present


